### PR TITLE
Added logo and ReadMe

### PR DESCRIPTION
**Pull request by callumrawlinson**
it looks way better now

### CODE REVIEW

**Comment by callumrawlinson** [comment]
@Endermanbugzjfc

**Review by Endermanbugzjfc — CHANGES_REQUESTED** [review]
Can you make the icon file transparent please?

**Comment by callumrawlinson** [comment]
yes. also i made a website https://callumrawlinson.github.io/clouria and i got a domain but havent linked it yet

**Comment by callumrawlinson** [comment]
island png-removebg-preview

**Comment by callumrawlinson** [comment]
@Endermanbugzjfc

**Review by callumrawlinson — COMMENTED** [review]
done

**Review by callumrawlinson — COMMENTED** [review]
fixed link

**Review by callumrawlinson — COMMENTED** [review]
done

**Comment by Endermanbugzjfc** [comment]
> yes. also i made a website https://callumrawlinson.github.io/clouria and i got a domain but havent linked it yet

Clouria is not a server making orgainization, it just one of the server that I am deving on. This plugin is make for the server originally and the server owner allowed me to open source this plugin. Please don't steal the server name. My own plugin workshop is [Lazuli Plugin Projects](https://github.com/zjfc-pm-pl)

**Comment by callumrawlinson** [comment]
ok i apologize! i didnt think about that. do you have any staff developer spaces on clouria>

**Comment by callumrawlinson** [comment]
i have delted the page i think.

**Comment by Endermanbugzjfc** [comment]
> ok i apologize! i didnt think about that. do you have any staff developer spaces on clouria>

Will ask the owner, his have school these weeks and haven't been online for 3 days already.

**Comment by callumrawlinson** [comment]
oh ok!

**Comment by callumrawlinson** [comment]
it is 11:26 for me right now. is it 19:26 for you

**Comment by Endermanbugzjfc** [comment]
> it is 11:26 for me right now. is it 19:26 for you

Yea

**Comment by callumrawlinson** [comment]
cool. did you need me to do anything else

**Comment by Endermanbugzjfc** [comment]
> cool. did you need me to do anything else

No thanks, at least now.

**Comment by callumrawlinson** [comment]
ok :} here where you need me

**Review by Endermanbugzjfc — APPROVED** [review]

**Review by callumrawlinson — COMMENTED** [review]
yes!

**Pull request merged**
